name: web_form
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_route: 0.4.4
  flutter_form_bloc: ^0.12.2
  cupertino_icons: ^0.1.3
  injectable: 0.3.0
  get_it: 4.0.1
  dartz: 0.8.9
  freezed_annotation: 0.7.1
  bloc: 3.0.0
  flutter_bloc: 3.2.0
  json_annotation: 3.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: 0.4.4
  injectable_generator: 0.3.4
  freezed: 0.10.6
  build_runner: 1.8.1
  json_serializable: 3.3.0
  test: 1.14.2

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true